name: portfolio
description: tsvillian Developer Portfolio.
publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.2
  flutter_svg: ^1.1.0
  font_awesome_flutter: ^10.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  responsive_builder: ^0.4.2
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
    - assets/projects/
    - assets/social_icons/
